- name: Reset k3s cluster nodes
  hosts: k3s_cluster
  become: true
  roles:
    - techno_tim.k3s_ansible.reset
  post_tasks:
    - name: Reboot and wait for node to come back up
      ansible.builtin.reboot:
        reboot_timeout: 3600
