apiVersion: v1
kind: Service
metadata:
  name: rancher
  namespace: cattle-system
spec:
  ipFamilyPolicy: PreferDualStack
  selector:
    app: rancher
  ports:
    - port: 80
      targetPort: 80
    - port: 443
      targetPort: 443
  type: LoadBalancer
